# Site settings
title: blog | mark joseph ronquillo
description: "projects, learnings, research and ideas."
url: "http://markronquillo.github.io"
header: mark ronquillo
tagline: a really cool tagline here
author:
  name: "Mark Joseph Ronquillo"
  email: "markronquillo23@gmail.com"
  url: "http://markronquillo.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "0.0.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
